### ISSUE TITLE
Remote Python Interpreters

### ISSUE THREAD

**Issue by mcepl** [python-rope/ropemacs#10]
Hi,

I'm experimenting with some changes to ropemacs so that it can use a Python interpreter on a different host than the one where Emacs is running.

In particular, I have Emacs running on my Mac, and Python running on a Vagrant/VirtualBox VM. I have several different projects on the VM, each using a different virtualenv. I wrote an Emacs package tramp-virtualenv[1](https://github.com/matthewlmcclure/tramp-virtualenv) that I use to tell Emacs which remote Python interpreter to use.

Now I'm working on changes in ropemacs[2](https://bitbucket.org/matthewlmcclure/ropemacs) so that it can also work with files I open via TRAMP and use the same remote Python interpreters and virtualenvs. As of opening this issue, my ropemacs can translate file paths on the Python host to their equivalent paths on the Emacs host and vice versa. I've tried it lightly, to get documentation, go to definition, and extract method.

Is this something you'd consider including in the upstream ropemacs?

**Comment by mcepl** [comment]
@matthewlmcclure I have pushed your trunk from Bitbucket to this repo as a separate branch https://github.com/python-rope/ropemacs/tree/matthewlmcclure Are you still using rope? Would you be willing to make it into a proper pull request here?

**Comment by matthewlmcclure** [comment]
I haven't been actively using rope, but I'm still interested. Thanks for
letting me know that someone else out there is interested too! I'll see if
I can give it another go soon.

Best,
Matt

On Fri, Feb 6, 2015 at 8:55 AM, Matěj Cepl <notifications@github.com> wrote:

> @matthewlmcclure <https://github.com/matthewlmcclure> I have pushed your
> trunk from Bitbucket to this repo as a separate branch
> https://github.com/python-rope/ropemacs/tree/matthewlmcclure Are you
> still using rope? Would you be willing to make it into a proper pull
> request here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-rope/ropemacs/issues/10#issuecomment-73239321>.
>



-- 
Matt McClure
http://matthewlmcclure.com
http://cens.io

**Comment by mcepl** [comment]
BTW, we have also discussion group on Google Groups https://groups.google.com/forum/#!forum/rope-dev (or http://dir.gmane.org/gmane.comp.python.rope if you are sane enough to prefer that).

**Comment by mcepl** [comment]
> I'll see if I can give it another go soon.

ping?

**Comment by matthewlmcclure** [comment]
Hi Matěj,

Sorry, but I don't think I will have time to work on this soon.

On Tuesday, May 3, 2016, Matěj Cepl <notifications@github.com> wrote:

> I'll see if I can give it another go soon.
>
> ping?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/python-rope/ropemacs/issues/10#issuecomment-216501646>
>


-- 
http://matthewlmcclure.com

**Comment by mcepl** [comment]
That's a pitty, I am afraid I won't be able to merge so large change.

**Comment by mcepl** [comment]
Respecitvely, do you want to say that this is all?
```
$ git diff --stat master
 ropemacs/__init__.py | 19 +++++++++++++++----
 1 file changed, 15 insertions(+), 4 deletions(-)
$ git push -u github matthewlmcclure
```
That sounds like too little to me.

**Comment by mcepl** [comment]
And, to your original question: of course, if I get the code with some tests (not sure, how to test it; some Mock?), and some documentation, then I would be very happy to merge it.

**Comment by matthewlmcclure** [comment]
@mcepl,

I reviewed the changes and tried it again. It still works for me, as described at <http://matthewlmcclure.com/s/2012/09/16/refactoring-python-remotely-in-emacs.html>.

The instructions there use a [slightly modified Pymacs][Pymacs] and an Emacs library [tramp-virtualenv][tramp-virtualenv].

[Pymacs]: https://github.com/matthewlmcclure/Pymacs/pull/1/files
[tramp-virtualenv]: https://github.com/matthewlmcclure/tramp-virtualenv

**Comment by mcepl** [comment]
OK, three things:

1. I don’t care about ``tramp-virtualenv``, ropemacs doesn’t use it
normally, does it? However, I do care about ``pymacs``. Is there a pull
request of your changes in Pymacs to the official upstream (whatever it is, PyPI seems to point to Francois Pinard and thus to https://github.com/pinard/Pymacs)? What’s the chance it will get merged there and to PyPI? I won’t ask ``rope`` users to use non-standard Pymacs.
2. Why does your pull request consists of four commits, when we are talking just about 15 lines added and 4 deleted in one file? Do we? Could you please squash just to the one with the proper [commit message](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)?
3. I still haven’t got any reply about tests. Would it be possible to make at least regression unit tests, so that we can follow whether it is not broken? For testing I wouldn’t mind if you require some additional packages from PyPI (e.g., Mock).

**Comment by matthewlmcclure** [comment]
1. I actually don't recall whether the Pymacs change is required. My comment at https://github.com/pinard/Pymacs/issues/32#issuecomment-7490071 suggests maybe not.
2. That's just how I committed as I was making the changes. It would be reasonable to squash the commits if you'd like.
3. I don't see any tests in the repository.

I'm not actively using this, so I don't think I will spend more time on it soon.

**Comment by mcepl** [comment]
> I'm not actively using this, so I don't think I will spend more time on it soon.

Ehm, https://github.com/pinard/Pymacs/issues/34#issuecomment-222578942.

Any thoughts?

**Comment by mcepl** [comment]
@emacsway ... you are my local hero for Emacs, what do you think?
