### ISSUE TITLE
The pymacs maintainer has changed; make pymacs easier to install

### ISSUE THREAD

**Issue by dgentry** [python-rope/ropemacs#36]
Hi,

Sadly, François Pinard died in 2014, so Pymacs was no longer maintained.  I searched for a new maintainer, but there doesn't seem to be one, so I've been doing it myself.  I released version 0.26 primarily to make installation a one-step process for most people, since it took me a long time to figure out the right way.  This should make it significantly easier for people to install ropemacs as a result.

Could you change the pointer to pymacs in the README from `https://github.com/pinard/Pymacs` to `https://github.com/dgentry/Pymacs`?  I can submit a pull request if that would be helpful, but an online edit using github might be even easier for you.

Thanks,
Dennis

**Comment by soupytwist** [comment]
Thank you for informing us of this and for continuing to maintain this library.
