### ISSUE TITLE
[help] How can I jump back after `rope-goto-definition`?

### ISSUE THREAD

**Issue by avatar-lavventura** [python-rope/ropemacs#41]
I am using `rope-goto-definition` to jump into a module's definition, [link][1]. But I cannot jump back to where I was. `xref-pop-marker-stack` says `Marker stack is empty`. Is it possible to jump back after running `rope-goto-definition`? Similiar behavior is done using `jedi:goto-definition-pop-marker`.

-------

My setup:

```
(require 'pymacs)
(pymacs-load "ropemacs" "rope-")
(setq ropemacs-enable-autoimport 't)
(setq ropemacs-autoimport-modules '("os" "shutil"))

(defun goto-def-or-jedi ()
  "Go to definition of thing at point or do an rgrep in project if that fails"
  (interactive)
  (condition-case nil (rope-goto-definition)
    (error (rope-goto-definition (thing-at-point 'symbol)))))
```

  [1]: https://github.com/python-rope/ropemacs#shortcuts

**Comment by mcepl** [comment]
ropemacs is completely unmaintained and abandoned. If you want to take over (and do something about those hanging pull requests), please, let me know.

**Comment by avatar-lavventura** [comment]
@mcepl I wish I had knowledge to handle all those pull requests. But even with its latest version `rope` works fine except jump back case. If I find a solution I would let you know.

**Comment by avatar-lavventura** [comment]
@mcepl In case this might help here is a solution: https://emacs.stackexchange.com/a/63848/18414

> you can put a mark at `rope-goto-definition` with https://www.emacswiki.org/emacs/auto-mark.el
>  
> 
>     (require 'auto-mark)
>       (setq auto-mark-command-class-alist
>             '((anything . anything)
>               (rope-goto-definition . jump)
>               (indent-for-tab-command . ignore)
>               (undo . ignore)))
>       (setq auto-mark-command-classifiers
>             (list (lambda (command)
>                     (if (and (eq command 'self-insert-command)
>                              (eq last-command-event ? ))
>                         'ignore))))
>       (global-auto-mark-mode 1)
> 
> Then you can use `pop-global-mark` or `pop-local-mark` depending on whether there is a change of buffer or not.
> unfortunately with this solution it is up to the user to manage when to use local or global marks.
